services:
  mongodb:
    image: mongo:8.2.5-noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-example}
    volumes:
      - mongo-data-dev:/data/db

volumes:
  mongo-data-dev:
